### ISSUE TITLE
Move list of urls to external json file

### ISSUE THREAD

**Issue by MatBenfield** [MatBenfield/morning.thechels.uk#1]
As a user I would like the list of news sources extracted from the python code to a separate Json file for easier maintenance and sharing.

**Comment by AmmaarAslam** [comment]
###  **You can use the following lines of code if you wish to read or write to an external json file in python:**

**Writing into the file:**
`import json`

`#define list with values`
`url_list = [1, 2, 3]`

`# open output file for writing`
`with open('listfile.json', 'w') as filehandle:`
`    json.dump(url_list, filehandle)`

**Reading the file:**
`import json`

`# open output file for reading`
`with open('listfile.json', 'r') as filehandle:`
     `url_list = json.load(filehandle)`
