### ISSUE TITLE
Data isn't in the format expected for rain percentage 

### ISSUE THREAD

**Issue by MatBenfield** [MatBenfield/morning.thechels.uk#13]
- Read the API docs,
- update the data item or update the wording to better reflect the data.

The wording is generated in the ``weather.py`` file (``line 30``)
and the api processing a few lines above that - should be pretty obvious.

**Comment by ShubhamPalriwala** [comment]
I'd like to take this up !

**Comment by Suvid-Singhal** [comment]
I have worked with this API before. Can I ake up this issue?
Also, one more thing can you please explain the issue once more. I didn't get what you want... :)

**Comment by MatBenfield** [comment]
Hi both, @ShubhamPalriwala you were first so if you want to pick this up that's fine, did you want to wait for hacktoberfest?

if not, then @Suvid-Singhal you can pick it up. :-)

thanks

**Comment by ShubhamPalriwala** [comment]
Yeah ! I'll be doing it during the Hacktoberfest if you dont mind.

**Comment by ShubhamPalriwala** [comment]
Hey @MatBenfield ,
I researched on the OpenWeatherMap API for a while now, so the rain parameter returns the amount of rainfall received in millimeters over the duration of 3 hours (if there is any otherwise it returns `null`).

And as we know, the amount of rainfall in mm isn't the percentage chance of rain.

Now, Should I change the wordings or find another API which supports all our requirements ?

**Comment by ShubhamPalriwala** [comment]
Shifting to another API might solve issue #16 as well.

**Comment by MatBenfield** [comment]
hi @ShubhamPalriwala , thanks for investigating. I think we should change the wording, and remove the amount of rain but provide the daily weather conditions (rather than current)
 [weather condition](https://openweathermap.org/weather-conditions) the descriptions here would be useful enough to plan accordingly.

"You can expect {conditions} for the day."

**Comment by ShubhamPalriwala** [comment]
Alright ! Thanks for the swift response !

**Comment by MatBenfield** [comment]
regarding #16, would you like to take this one as well? I think using the `one call API` there is a section to get the daily summary rather than the current I had initially coded for. If you want to tackle both issues that would be fantastic. Thanks

**Comment by ShubhamPalriwala** [comment]
Yeah Sure !

**Comment by ShubhamPalriwala** [comment]
Please check the PR #17 regarding this !
