### ISSUE TITLE
Add local coronavirus data section - using python

### ISSUE THREAD

**Issue by MatBenfield** [MatBenfield/morning.thechels.uk#15]
As a user I would like to see my local coronavirus data as published by [gov.uk](https://coronavirus.data.gov.uk/developers-guide#latestby-example)

**Describe the solution you'd like**

- Add a section to the html (above the news)
- create a new script ``coronavirus.py``.
- using the python examples from the above linked site
- ideally post the last 3 days worth of cases and deaths as bulleted list
- use GitHub secrets for the location and pass this in through the build

**Comment by malathit** [comment]
Shall I take this up for the *Hacktoberfest*?

**Comment by malathit** [comment]
Hey I can't reuse an existing secret like `COUTRY_CODE` here right? I need to create a new secret that will be accepted by the api above. Can you please confirm this? Also, I can't run the github action as they are failing. Is there a way I can test the code?

**Comment by MatBenfield** [comment]
in the docs they mention ``filters=areaName=Cambridge`` so I have an existing secret that is CITY_CODE, Although you won't be able to test this locally, you should be able see the build succeed on the branch.
