### ISSUE TITLE
Weather report is for the time it is run and not the daily summary

### ISSUE THREAD

**Issue by MatBenfield** [MatBenfield/morning.thechels.uk#16]
**Describe the bug**
The temperatures displayed on screen are the current, highs and lows for the hour in which the code was run and not the daily highs and lows

**Expected behaviour**
As a user I would like to know the weather for the entire day so I can plan accordingly.

**Comment by ShubhamPalriwala** [comment]
Hey ! Can I resolve this issue too just after resolving the Rain Data Value error ?

**Comment by ShubhamPalriwala** [comment]
Hey, so one-call API requires the latitude and longitude of the location.

Do you want me to use another API that converts the city name to its coordinates or continue setting up assuming you'll use the coordinates itself ?

**Comment by MatBenfield** [comment]
Yeh, let's work on the basis long and late can be stored as GitHub secrets and passed through the build.yml file to the code. 👍

**Comment by ShubhamPalriwala** [comment]
Please check the PR #17 regarding this !
